package com.example.un_app.services;

public enum CategoryOption {
    GDP, FDI_INFLOWS, FDI_OUTFLOWS, IMPORT_EXPORT_FLOW, CONTRIBUTION_TO_GDP,
    CREDIT, FERTILIZERS, FERTILIZERS_PRODUCTION, RESERVES, GNI, TOTAL_DEBT, GNI_CURRENT
}
